#!/usr/bin/env python3
"""Regenerate docs/osc-map.md from spec/mapping.yaml."""

from __future__ import annotations

import os

from build_tosc import ROOT, load_spec

OUT = os.path.join(ROOT, "docs", "osc-map.md")


def main() -> int:
    spec = load_spec()
    res, td, grid = spec["resolume"], spec["touchdesigner"], spec["grid"]
    conns = spec["connections"]
    lines = [
        "# OSC address map",
        "",
        "Generated by `tools/dump_map.py` — edit `spec/mapping.yaml`, not this file.",
        "",
        "## Connections",
        "",
        "| Slot | Target | Host | Port |",
        "| --- | --- | --- | --- |",
    ]
    for name, cfg in conns.items():
        lines.append(f"| {cfg['slot']} | {name} | {cfg['host']} | {cfg['port']} |")

    lines += ["", "## Resolume Arena", "", "| Control | Address | Sends |", "| --- | --- | --- |"]
    lines.append(f"| Clip launch ({grid['layers']}x{grid['clips']}) | "
                 f"`{res['clip_connect']}` | 1.0 on press |")
    lines.append(f"| Layer opacity | `{res['layer_opacity']}` | float 0..1 |")
    lines.append(f"| Layer bypass | `{res['layer_bypass']}` | 0/1 toggle |")
    lines.append(f"| Layer solo | `{res['layer_solo']}` | 0/1 toggle |")
    lines.append(f"| Layer clear | `{res['layer_clear']}` | 1.0 on press |")
    lines.append(f"| Master | `{res['master']}` | float 0..1 |")
    lines.append(f"| Speed | `{res['speed']}` | float 0..1 |")
    lines.append(f"| Tap tempo | `{res['tempo_tap']}` | 1.0 on press |")
    lines.append(f"| Resync | `{res['tempo_resync']}` | 1.0 on press |")

    lines += ["", "### FX page", "",
              "One knob and one bypass per layer per effect. The effect must already exist "
              "in the layer's effect chain in Arena.", "",
              "| Knob | Address |", "| --- | --- |"]
    for fx in res["fx_names"][: grid["fx_params"]]:
        lines.append(f"| {fx['name']} | "
                     f"`{res['fx_param'].format(layer='{layer}', fx=fx['fx'], param=fx['param'])}` |")

    lines += ["", "## TouchDesigner", "", "| Control | Address | Count |", "| --- | --- | --- |"]
    lines.append(f"| Faders | `{td['fader']}` | {grid['td_faders']} |")
    lines.append(f"| Toggles | `{td['toggle']}` | {grid['td_toggles']} |")
    lines.append(f"| Triggers | `{td['trigger']}` | {grid['td_toggles']} |")
    lines.append(f"| XY pads | `{td['pad']}/x`, `{td['pad']}/y` | {grid['td_pads']} |")
    lines.append(f"| Intensity | `{td['intensity']}` | 1 |")
    lines.append(f"| Scene | `{td['scene']}` | 1 |")
    lines.append(f"| Blackout | `{td['blackout']}` | 1 |")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
